app: fonction.o main.o
	gcc -o app fonction.o main.o -lSDL2 -lSDL2_image -lSDL2_ttf
fonction.o: fonction.c
	gcc -o fonction.o -c fonction.c -lSDL2 -lSDL2_image -lSDL2_ttf
main.o: main.c fonction.h
	gcc -o main.o -c main.c -lSDL2 -lSDL2_image -lSDL2_ttf